name: Prod Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:  
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Keep credentials so downstream steps can push tags
          persist-credentials: true
          # Fetch full history and tags so semver can calculate correctly
          fetch-depth: 0

      - name: Configure Git for tagging
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Semver Release
        uses: huggingface/semver-release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}