name: Prod Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:  
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semver Release
        uses: huggingface/semver-release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}